# modules/config.py

MODEL_OBB_PATH = "model/best0602-obb.pt"
MODEL_HBB_PATH = "model/best-hbb.pt"

IMGSZ_OBB = 960
IMGSZ_HBB = 416
HBB_CONF = 0.60

DEFAULT_SKIP_FRAMES = 10
DEFAULT_TOTAL_SHRIMP = 6
DEFAULT_KEYFRAMES = 12
DEFAULT_TIME_WINDOW_SEC = 10

ID_MATCH_DISTANCE = 260
MALE_RATE_THRESHOLD = 0.50
MIN_OBSERVATIONS_PER_SHRIMP = 3
RELIABLE_FORCED_ID_RATE = 35
